#!/usr/bin/env bash

export JH_SECRET_MARK="🔒"

export JH_CONFIG_TEST="test"

# pcloud shared-root app
# configured here: https://docs.pcloud.com/my_apps/
export JH_PASS_PCLOUD_RO_CLIENT_ID="🔒U2FsdGVkX19hW7/a8hxb6X+/xWEaRAylMx4Y78laL8Y="
export JH_PASS_PCLOUD_RO_CLIENT_SECRET="🔒U2FsdGVkX18BM5skF0UwiytcxPoyqfHQoCEETOLsrJm+DtPvQ1u2Lq2tESxnc+1b"
export JH_PASS_PCLOUD_RW_CLIENT_ID="🔒U2FsdGVkX1+wHolIYEiPXUmcp2L0zVeKj5EQ3ODhEbs="
export JH_PASS_PCLOUD_RW_CLIENT_SECRET="🔒U2FsdGVkX18SgIaCVlVe8Ixg+ILkWQiy9FsEnpALY8jzuIWI4szwnR97hxhcMsDE"

export JH_CAMERA_HOST="192.168.1.7"
export JH_CAMERA_USER="🔒U2FsdGVkX18DVNatc+bToj+5E0LWY3NE4KeL91FrCGs="
export JH_CAMERA_PASS="🔒U2FsdGVkX1+mtUqmulHFiMpJNUq7PBjxy/N+HPs4P1Q="

export JH_DOCKER_HUB_TOKEN="🔒U2FsdGVkX1/bWiFY4wrAYDyioZ01cnaTfnDzYaVtTy0N79H+bcnMSAg/0N2sB3vawMuNq8XSt30cqsbR9hibKw=="

export JH_DEFAULT_PWD="🔒U2FsdGVkX1+kT31LidX6KgzOU0Q8awukdkCtyjmxOg8="

export JH_CRYPTOMEDIC_DATABASE_USER="🔒U2FsdGVkX18E4X9KPoiasStnwKvBUAUcaefUm0/Ec8I="
export JH_CRYPTOMEDIC_DATABASE_PASS="🔒U2FsdGVkX1+9PN26IWaHLLE/VI4nlLrECVIc6HFaHrA="
export JH_CRYPTOMEDIC_SECURITY_ADMIN="🔒U2FsdGVkX19aZ1isag+KiFwwSrtpLHAYmsRGGM6TE7w="
export JH_CRYPTOMEDIC_SECURITY_KEY="🔒U2FsdGVkX1/PTaVnZhwwkO+7KrcaZVIMlzhR0BoEoVs="
export JH_CRYPTOMEDIC_SECURITY_TOKEN="🔒U2FsdGVkX19fJaTJ8bHHGDYKY08wNV3jb4yZpIjWb36EKy5N096icf0tSPMu7kcL+fLbuhYpfrKGkzKFwSLarw=="
export JH_CRYPTOMEDIC_SECURITY_RANDOM="🔒U2FsdGVkX1/Csc7No4Q0mS4EqIALvWWvA6ezAsgxZYBU/HaWzb2S2P5GuM3wL4ic2d7KmdmLDxsNg9MB3oQcGw=="

export JH_CAMERA_URL="🔒U2FsdGVkX1/rGJBd6VQGqMYp2hz8mgSFh65+7DeulRRLK2+TA0HLENuBuiCPRdTO5EdZiqjumRVUFRAumG1taw=="

# Not imported:

# JH_NAS_USER
# JH_NAS_PASS
# JH_HOSTS_KIOSK_IP
